#ifndef __EB_BOARD_CONFIG_H__
#define __EB_BOARD_CONFIG_H__


#define IO_ADDR_START       CONFIG_IO_START
#define IO_ADDR_END         CONFIG_IO_END
#define RAM_ADDR_START      CONFIG_RAM_START
#define RAM_ADDR_END        CONFIG_RAM_END

#define EXBOOT_ADDR_START   CONFIG_EXBOOT_START
#define EXBOOT_ADDR_END     CONFIG_EXBOOT_END

#define KIRK_LOAD_ALIGN     CONFIG_KIRK_LOAD_ALIGN

#endif
