/*
 * thread_privilege.h
 *
 *  Created on: 2022Äê12ÔÂ2ÈÕ
 *      Author: Test
 */

#ifndef SDK_LIB_PLATFORM_INCLUDE_THREAD_PRIVILEGE_H_
#define SDK_LIB_PLATFORM_INCLUDE_THREAD_PRIVILEGE_H_

typedef enum{
	THREAD_CTL_IO,
	//	THREAD_CTL_NAME,
}THREAD_SETTING_INDEX;


//#define THREAD_CTL_IO
//#define THREAD_CTL_ALIGN_FAULT
//#define THREAD_CTL_NAME
//#define THREAD_CTL_ONE_THREAD_CONT
//#define THREAD_CTL_ONE_THREAD_HOLD
//#define THREAD_CTL_RUNMASK
//#define THREAD_CTL_RUNMASK_GET_AND_SET
//#define THREAD_CTL_RUNMASK_GET_AND_SET_INHERIT
//#define THREAD_CTL_THREADS_CONT
//#define THREAD_TL_THREADS_HOLD



#endif /* SDK_LIB_PLATFORM_INCLUDE_THREAD_PRIVILEGE_H_ */
