/*
 * thread_schedule.h
 *
 *  Created on: 2022Äê12ÔÂ1ÈÕ
 *      Author: Test
 */

#ifndef SDK_LIB_PLATFORM_INCLUDE_THREAD_SCHEDULE_H_
#define SDK_LIB_PLATFORM_INCLUDE_THREAD_SCHEDULE_H_

typedef enum{
    SCHEDULE_POLICY_NORMAL,
	SCHEDULE_POLICY_RR,
	SCHEDULE_POLICY_FIFO,
}SCHEDULE_POLICY;

#define THREAD_PRIORITY_LEVEL_NORMAL (10)

#define THREAD_PRIORITY_LEVEL_NODISTURB (128)

#define THREAD_SCHEDULE_QUANTUM (4)

#endif /* SDK_LIB_PLATFORM_INCLUDE_THREAD_SCHEDULE_H_ */
