/*
 * atomic.S
 *
 *  Created on: 2022Äê11ÔÂ14ÈÕ
 *      Author: Test
 */

.globl	atomic_add
.globl	atomic_add_value
atomic_add:
atomic_add_value:
		mov pc, lr


.globl	atomic_clr
.globl	atomic_clr_value
atomic_clr:
atomic_clr_value:

		mov pc, lr

.globl	atomic_set
.globl	atomic_set_value
atomic_set:
atomic_set_value:
		mov pc, lr

.globl	atomic_sub
.globl	atomic_sub_value
atomic_sub:
atomic_sub_value:
		mov pc, lr


.globl	atomic_toggle
.globl	atomic_toggle_value
atomic_toggle:
atomic_toggle_value:
		mov pc, lr

